name: test

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  python-3.8-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test with unittest
      run: |
        python3 -m unittest discover

  python-3.8-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test with unittest
      run: |
        python3 -m unittest discover

  python-3.8-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test with unittest
      run: |
        python3 -m unittest discover
